#!/bin/bash

# setup-worktrees.sh
# Automatically creates 5 git worktrees, assigns agents, sets up shell aliases.
# Run once from your main repo root.
#
# Usage:
#   chmod +x scripts/setup-worktrees.sh
#   ./scripts/setup-worktrees.sh
#
# What it does:
#   1. Creates 5 worktrees in sibling directories (../repo-1 through ../repo-5)
#   2. Each worktree gets its own branch
#   3. Writes worktree-map.json to orchestration/
#   4. Appends shell aliases to ~/.zshrc or ~/.bashrc

set -e

REPO_NAME=$(basename "$(pwd)")
PARENT_DIR=$(dirname "$(pwd)")
if [ -f "$HOME/.zshrc" ] && [ "$SHELL" = "/bin/zsh" ]; then
  SHELL_RC="$HOME/.zshrc"
else
  SHELL_RC="$HOME/.bashrc"
fi

echo "🎭 Setting up 5 Claude Code worktrees for: $REPO_NAME"
echo ""

# Agent assignments
declare -a AGENTS=("Backend Architect" "Frontend Developer" "Security Engineer" "DevOps Automator" "Reality Checker")
declare -a ALIASES=("za" "zb" "zc" "zd" "ze")
declare -a BRANCHES=("feat/backend" "feat/frontend" "feat/security" "feat/devops" "analysis")
declare -a COLORS=("\033[0;34m" "\033[0;32m" "\033[0;31m" "\033[0;35m" "\033[0;33m")
RESET="\033[0m"

# Create orchestration dir if needed
mkdir -p orchestration

# Build worktree map JSON
WORKTREE_MAP='{"worktrees":['

for i in "${!AGENTS[@]}"; do
  WORKTREE_DIR="$PARENT_DIR/${REPO_NAME}-wt-$((i+1))"
  AGENT="${AGENTS[$i]}"
  ALIAS="${ALIASES[$i]}"
  BRANCH="${BRANCHES[$i]}"
  COLOR="${COLORS[$i]}"

  echo -e "${COLOR}[$((i+1))/5] Setting up: $AGENT${RESET}"
  echo -e "     Worktree: $WORKTREE_DIR"
  echo -e "     Branch:   $BRANCH"
  echo -e "     Alias:    $ALIAS"

  # Create the worktree + branch
  if [ -d "$WORKTREE_DIR" ]; then
    echo "     → Already exists, skipping"
  else
    git worktree add "$WORKTREE_DIR" -b "$BRANCH" 2>/dev/null || \
    git worktree add "$WORKTREE_DIR" "$BRANCH" 2>/dev/null
    echo "     → Created ✅"
  fi

  # Add to JSON map
  [ $i -gt 0 ] && WORKTREE_MAP+=","
  WORKTREE_MAP+="{\"index\":$((i+1)),\"name\":\"${REPO_NAME}-wt-$((i+1))\",\"path\":\"$WORKTREE_DIR\",\"alias\":\"$ALIAS\",\"agent\":\"$AGENT\",\"branch\":\"$BRANCH\"}"

  echo ""
done

WORKTREE_MAP+=']}'

# Write worktree map
echo "$WORKTREE_MAP" | python3 -m json.tool > orchestration/worktree-map.json
echo "✅ Written: orchestration/worktree-map.json"
echo ""

# Write shell aliases
echo "# Claude Code worktree aliases — auto-generated by setup-worktrees.sh" >> "$SHELL_RC"
for i in "${!AGENTS[@]}"; do
  WORKTREE_DIR="$PARENT_DIR/${REPO_NAME}-wt-$((i+1))"
  ALIAS="${ALIASES[$i]}"
  AGENT="${AGENTS[$i]}"
  echo "alias $ALIAS='cd $WORKTREE_DIR && echo \"🎭 $AGENT\" && claude'" >> "$SHELL_RC"
done
echo "alias zp='cd $(pwd) && echo \"🎭 Project Manager\" && claude'" >> "$SHELL_RC"
echo "" >> "$SHELL_RC"

echo "✅ Shell aliases written to $SHELL_RC"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Setup complete! Restart your shell or run:"
echo "   source $SHELL_RC"
echo ""
echo "Then use these aliases to jump to each agent:"
for i in "${!AGENTS[@]}"; do
  echo "   ${ALIASES[$i]}  →  ${AGENTS[$i]}"
done
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 At the start of each agent session, paste this:"
echo ""
echo "Before starting:"
echo "1. Read orchestration/task-registry.json"
echo "2. Read orchestration/context-handoff.json"
echo "3. Claim your task with status: in_progress"
echo "4. Only touch files in your task's files_owned"
echo "5. Write to context-handoff.json when done"
